### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [dennis-sheil/android-spreadsheet#2]
Hi,

Since this app is GNU GPL v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/). The only problem I see here is [this jar](https://github.com/dennis-sheil/android-spreadsheet/blob/master/app/libs/poi-all.jar), is it possible to remove it or replace it with a gradle dependency.

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by dennis-sheil** [comment]
While the app can load a spreadsheet, I think it needs a lot more functionality done before it can be released.

I have no qualm with it being included in F-droid, or someone else talks to F-droid about it, but I currently do not plan to release it on Google Play or other platforms until more features are done.

**Comment by Poussinou** [comment]
I thought it could be of some interest for certain F-Droid users to at least visualize a spreadsheet (me, for example). If we include the app, you could then tag new releases and increment version in the gradle file, and users would get updates easily and quickly. Choice is yours...

**Comment by jasonkhanlar** [comment]
I cannot find a single open source free software spreadsheet editor software application to use on Android operating system other than this package. No calligra, gnumeric, libreoffice/openoffice (only viewer, no editor), pyspread.

**Comment by 4g4p3** [comment]
@jasonkhanlar 

Same problem. Actually, which app are you using to solve this need?
